name: Build ISO

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: Install archiso
        run: |
          pacman -Syyu --noconfirm archiso git
          echo "VER=$(date +%Y.%m.%d)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        run: |
          ./apply-patches.sh
          mkarchiso -v -o ./out ./releng

      - name: Upload ISO
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VER }}
          files: |
              ./out/*.iso
