name: Build ISO

on:
  schedule:
    - cron: '0 18 1 * *'
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: Install archiso
        run: pacman -Syyu --noconfirm archiso

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        run: mkarchiso -v -o ./out ./profile

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: isofile
          path: ./out/*.iso